name: Compile Apache Ranger
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 4 * * 3'

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  discover-new-releases:
    name: Discover releases
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.discover-releases.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: apache-ranger-compiled

      - name: Checkout Apache Ranger repository
        uses: actions/checkout@v3
        with:
          repository: apache/ranger
          fetch-depth: 0
          path: ranger

      - name: Discover Apache Ranger releases
        id: discover-releases
        run: |
          compiled=$(cat ./apache-ranger-compiled/compiled)
          versions=$((git --git-dir ./ranger/.git tag | grep release-ranger- | sed -e "s/release-ranger-//g" | grep -v "${compiled}") || echo "none")
          if [[ "${versions}" == "none" ]]; then
            matrix="none"
          else
            matrix=$(jq -cRn '[inputs as $version | {version: $version}] | { include: . }' <<<"$versions")
          fi
          echo "::set-output name=matrix::$matrix"
  
  build:
    name: Build Apache Ranger ${{ matrix.version }}
    if: ${{ needs.discover-new-releases.outputs.matrix != 'none' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.discover-new-releases.outputs.matrix) }}
    runs-on: ubuntu-latest
    needs: discover-new-releases
    steps:
      - name: Download Apache Ranger ${{ matrix.version }}
        id: download-ranger 
        run: |
          wget -nv "https://archive.apache.org/dist/ranger/${{ matrix.version }}/apache-ranger-${{ matrix.version }}.tar.gz" -O "apache-ranger.tar.gz"
          wget -nv "https://archive.apache.org/dist/ranger/${{ matrix.version }}/apache-ranger-${{ matrix.version }}.tar.gz.asc" -O "apache-ranger.tar.gz.asc"
          wget -nv "https://archive.apache.org/dist/ranger/KEYS" -O "ranger-KEYS"
          gpg --import ranger-KEYS
          gpg --verify apache-ranger.tar.gz.asc apache-ranger.tar.gz
          if [[ "${{ matrix.version }}" == "2.2.0" ]]; then 
            mkdir apache-ranger-${{ matrix.version }}
            tar zxf apache-ranger.tar.gz -C apache-ranger-${{ matrix.version }}
          else 
            tar zxf apache-ranger.tar.gz
          fi
          cd apache-ranger-${{ matrix.version }}
          java_version=$(cat pom.xml | grep -Eo "<java.version.required>.*</java.version.required>" | sed "s/<java.version.required>//g" | sed "s </java.version.required>  g")
          if [[ "$java_version" == "1.8" ]]; then
            java_version=8.0.345+1
          fi
          echo "::set-output name=java-version::$java_version"

      - name: Set up JDK ${{ steps.download-ranger.outputs.java-version }}
        uses: actions/setup-java@v3.9.0
        with:
          java-version: ${{ steps.download-ranger.outputs.java-version }}
          java-package: jdk
          architecture: x64
          distribution: temurin
          cache: 'maven'

      - name: Build Apache Ranger ${{ matrix.version }}
        run: |
          cd apache-ranger-${{ matrix.version }}
          if dpkg --compare-versions "${{ matrix.version }}" "lt" "2.1.0"; then
            mvn clean compile package assembly:assembly -DskipTests
          else
            mvn clean compile package -DskipTests
          fi
        
      - name: Create release ${{ matrix.version }}
        id: create-release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ matrix.version }}
          release_name: Apache Ranger ${{ matrix.version }}
          draft: false
          prerelease: false
        
      - name: Publish Apache Ranger ${{ matrix.version }}
        run: |
          cd apache-ranger-${{ matrix.version }}/target
          for asset in *.{tar.gz,jar}; do
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: $(file -b --mime-type $asset)" --data-binary @$asset "${{ steps.create-release.outputs.upload_url }}=$(basename $asset)"
          done

      - name: Checkout Apache Ranger compiled
        uses: actions/checkout@v3
        with:
          path: apache-ranger-compiled

      - name: Check Apache Ranger ${{ matrix.version }} as released
        run: |
          cd apache-ranger-compiled
          git config user.email "z0beat@gmail.com"
          git config user.name "zer0beat"
          git pull --rebase origin main
          echo ${{ matrix.version }} >> ./compiled
          git add compiled
          git commit -m "Check Apache Ranger ${{ matrix.version }} as released [skip actions]"
          git push origin main
